### ISSUE TITLE
code of random-mixing

### ISSUE THREAD

**Issue by ZhaoJY1** [SunnyCYC/aug4mss#1]
Hello, is it possible for you to also share code for random-mixing of collected solo recordings of piano and violin, as you mentioned in your paper?
Thanks!!!

**Comment by SunnyCYC** [comment]
Hi, I actually follow open-unmix's framework for random-mixing. They provide the source code here : https://github.com/sigsep/open-unmix-pytorch/blob/master/data.py#L387
If you have different dataset/file structure, you may also find useful information here:
https://github.com/sigsep/open-unmix-pytorch/blob/master/docs/training.md

**Comment by ZhaoJY1** [comment]
Thanks for the hint!
