### ISSUE TITLE
Inference.py

### ISSUE THREAD

**Issue by kevinlin91** [SunnyCYC/aug4mss#2]
Hi, thanks for the great work. I saw there are inference.py and SeparateModules.py in the README, Contents section. But I cannot find these files in the repo. Are these two files provided?
Thank you.

**Comment by SunnyCYC** [comment]
Hi, 
I just uploaded them. But I didn't check if they can work directly.
If there's any further issue, please let me know.
Thank you!

**Comment by kevinlin91** [comment]
Sure. I'll try it.
Thank you!
