### ISSUE TITLE
unclear how to make Inference.py actually work

### ISSUE THREAD

**Issue by jsphweid** [SunnyCYC/aug4mss#3]
I get this error when trying to run Inference.py:

```python
Traceback (most recent call last):
  File "Inference.py", line 55, in <module>
    getEstimates_fromMpth(model_path, tsong_list)
  File "Inference.py", line 38, in getEstimates_fromMpth
    estimates = separate(audio=tsong_audio, targets=['violin', 'piano'],
  File "/Users/me/git/personal/aug4mss/SeparateModules.py", line 140, in separate
    unmix_target = load_model(
  File "/Users/me/git/personal/aug4mss/SeparateModules.py", line 60, in load_model
    unmix = model.OpenUnmix(
TypeError: __init__() got an unexpected keyword argument 'n_fft'
```

The issue seems to be that [your code is passing in two arguments](https://github.com/SunnyCYC/aug4mss/blob/2c4f7e4d93070e4bbea902df8989cd5dc4982d70/SeparateModules.py#L61-L62) that [OpenUnmix doesn't seem to accept](https://github.com/sigsep/open-unmix-pytorch/blob/master/openunmix/model.py#L15-L41).

(It also appears there could be a type mismatch with the max_bin argument.)

I explored OpenUnmix code a bit looking over past commits and releases trying to see if that class used to accept the args you are passing, but I couldn't find a commit in my brief search that contained it.

It's unclear how this is supposed to function. And as a side note, why not just include the files directly in your project? [The license is MIT](https://github.com/sigsep/open-unmix-pytorch/blob/master/LICENSE) which is one of the most liberal licenses out there...

**Comment by SunnyCYC** [comment]
Hi, 

It seems that official OpenUmix has modified their model.py. That's why the arguments are not accepted.
I've uploaded the old model.py. Please see if it works.

I didn't include the file because it seemed not necessary at that time to copy other people's scripts to my repo.
But still thanks for your suggestions!

**Comment by jsphweid** [comment]
Everything works. Thank you for your quick response!
