### ISSUE TITLE
 GoogleDrive link invalid

### ISSUE THREAD

**Issue by hewei9** [SunnyCYC/aug4mss#5]
Hi! Thanks for the great work. The current GoogleDrive link is no longer valid. Is it possible for you to upload a new link or provide the pretrained model?Really appreciate it!

**Comment by SunnyCYC** [comment]
Hi thanks for asking. I've updated the googledrive link. Please see if it works.

**Comment by hewei9** [comment]
Thanks so much! It works^_^.
